[NbConvertApp] Converting notebook ./01_BOOST-GP_simulate_SVGs.ipynb to html

 *** caught bus error ***
address 0x155338ea145c, cause 'non-existent physical address'
An irrecoverable exception occurred. R is aborting now ...
Traceback (most recent call last):
  File "/home/rs619065/miniconda3/envs/r-4.1/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/home/rs619065/miniconda3/envs/r-4.1/lib/python3.8/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/rs619065/miniconda3/envs/r-4.1/lib/python3.8/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/home/rs619065/miniconda3/envs/r-4.1/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 361, in start
    self.convert_notebooks()
  File "/home/rs619065/miniconda3/envs/r-4.1/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 533, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/rs619065/miniconda3/envs/r-4.1/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 498, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/rs619065/miniconda3/envs/r-4.1/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 427, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/rs619065/miniconda3/envs/r-4.1/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 186, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/rs619065/miniconda3/envs/r-4.1/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 204, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/rs619065/miniconda3/envs/r-4.1/lib/python3.8/site-packages/nbconvert/exporters/html.py", line 145, in from_notebook_node
    return super().from_notebook_node(nb, resources, **kw)
  File "/home/rs619065/miniconda3/envs/r-4.1/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 376, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/home/rs619065/miniconda3/envs/r-4.1/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/rs619065/miniconda3/envs/r-4.1/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 323, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/rs619065/miniconda3/envs/r-4.1/lib/python3.8/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/home/rs619065/miniconda3/envs/r-4.1/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 84, in preprocess
    self.preprocess_cell(cell, resources, index)
  File "/home/rs619065/miniconda3/envs/r-4.1/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 105, in preprocess_cell
    cell = self.execute_cell(cell, index, store_history=True)
  File "/home/rs619065/miniconda3/envs/r-4.1/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/rs619065/miniconda3/envs/r-4.1/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/rs619065/miniconda3/envs/r-4.1/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/rs619065/miniconda3/envs/r-4.1/lib/python3.8/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/rs619065/miniconda3/envs/r-4.1/lib/python3.8/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
for(i in c(0:9)){
    adata <- read_h5ad(glue::glue("../../data/simulation/svgs/adata_rep_{i}.h5ad"))
    counts = as.matrix(adata$layers[['counts']])
    loc <- as.data.frame(adata$obsm[['spatial']])
    
    df <- as.data.frame(boost.gp(Y = counts, loc = loc, iter=100))
    
    df_var <- adata$var
    df_var$spatially_variable <- as.integer(df_var$spatially_variable)

    df <- df[rownames(df_var), ]
    df$spatially_variable <- as.integer(df_var$spatially_variable)
    df <- df[, c("pval", "spatially_variable")]
    
    write.csv(df, file=glue::glue("./svgs/rep_{i}.csv"), quote=FALSE)

}
------------------

Error in res$logBF[(burn + 1):iter, ]: subscript out of bounds
Traceback:

1. as.data.frame(boost.gp(Y = counts, loc = loc, iter = 100))
2. boost.gp(Y = counts, loc = loc, iter = 100)
ERROR: Error in res$logBF[(burn + 1):iter, ]: subscript out of bounds


